version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: flake8 ./pydoro/
          name: Lint
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: python -m pytest
          name: Test
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: make build
          name: Build

workflows:
  main:
    jobs:
      - lint
      - test
      - build
