version: 2.1

orbs:
  python: circleci/python@1.2.1
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: flake8 ./pydoro/
          name: Lint
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: python -m pytest
          name: Test
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: make build
          name: Build
      - persist_to_workspace:
          root: ./
          paths:
            - dist.zip
  upload:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/copy:
          from: /tmp/workspace/dist.zip
          to: s3://pydoro-artifacts/backend/${CIRCLE_SHA1}.zip


workflows:
  main:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test
      - upload:
          requires:
            - build
